sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/desilover26/android_device_Tecno_ID5A.git device/TECNO/Tecno_ID5A
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_h398-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/h398/recovery.img $HOME/twrp/TWRP-$version-h398-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: TwrpBuilder/android_device_infinix_h398
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
