LOCAL_PATH := device/$$BRAND$$/$$DEVICE$$

PRODUCT_MAKEFILES := $(LOCAL_PATH)/omni_$$TECNO-ID5a$$.mk
LOCAL_PATH := device/TECNO/TECNO-ID5a/

PRODUCT_MAKEFILES := $(LOCAL_PATH)/omni_TECNO ID5a.mk
